In [12]:
import pandas as pd
import numpy as np

data  = pd.read_csv('./master.csv')

data.head()

data1=data[data['year']==2015]

data1

,country,year,sex,age,suicides_no,population,suicides/100k pop,country-year,HDI for year,gdp_for_year ($),gdp_per_capita ($),generation
576,Antigua and Barbuda,2015,female,55-74 years,1,6403,15.62,Antigua and Barbuda2015,NaN,"1,364,863,037",14853,Boomers
577,Antigua and Barbuda,2015,female,15-24 years,0,8561,0.00,Antigua and Barbuda2015,NaN,"1,364,863,037",14853,Millenials
578,Antigua and Barbuda,2015,female,25-34 years,0,7740,0.00,Antigua and Barbuda2015,NaN,"1,364,863,037",14853,Millenials
579,Antigua and Barbuda,2015,female,35-54 years,0,15323,0.00,Antigua and Barbuda2015,NaN,"1,364,863,037",14853,Generation X
580,Antigua and Barbuda,2015,female,5-14 years,0,8239,0.00,Antigua and Barbuda2015,NaN,"1,364,863,037",14853,Generation Z
581,Antigua and Barbuda,2015,female,75+ years,0,1724,0.00,Antigua and Barbuda2015,NaN,"1,364,863,037",14853,Silent
582,Antigua and Barbuda,2015,male,15-24 years,0,8331,0.00,Antigua and Barbuda2015,NaN,"1,364,863,037",14853,Millenials
583,Antigua and Barbuda,2015,male,25-34 years,0,7059,0.00,Antigua and Barbuda2015,NaN,"1,364,863,037",14853,Millenials
584,Antigua and Barbuda,2015,male,35-54 years,0,13370,0.00,Antigua and Barbuda2015,NaN,"1,364,863,037",14853,Generation X
585,Antigua and Barbuda,2015,male,5-14 years,0,8268,0.00,Antigua and Barbuda2015,NaN,"1,364,863,037",14853,Generation Z
586,Antigua and Barbuda,2015,male,55-74 years,0,5784,0.00,Antigua and Barbuda2015,NaN,"1,364,863,037",14853,Boomers
587,Antigua and Barbuda,2015,male,75+ years,0,1087,0.00,Antigua and Barbuda2015,NaN,"1,364,863,037",14853,Silent
948,Argentina,2015,male,75+ years,245,712691,34.38,Argentina2015,NaN,"594,749,285,413",14981,Silent
949,Argentina,2015,male,15-24 years,656,3500580,18.74,Argentina2015,NaN,"594,749,285,413",14981,Millenials
950,Argentina,2015,male,55-74 years,431,3011963,14.31,Argentina2015,NaN,"594,749,285,413",14981,Boomers
951,Argentina,2015,male,25-34 years,465,3289927,14.13,Argentina2015,NaN,"594,749,285,413",14981,Millenials
952,Argentina,2015,male,35-54 years,633,5166179,12.25,Argentina2015,NaN,"594,749,285,413",14981,Generation X
953,Argentina,2015,female,15-24 years,153,3394201,4.51,Argentina2015,NaN,"594,749,285,413",14981,Millenials
954,Argentina,2015,female,55-74 years,125,3520779,3.55,Argentina2015,NaN,"594,749,285,413",14981,Boomers
955,Argentina,2015,female,25-34 years,114,3235582,3.52,Argentina2015,NaN,"594,749,285,413",14981,Millenials
956,Argentina,2015,female,35-54 years,166,5301368,3.13,Argentina2015,NaN,"594,749,285,413",14981,Generation X
957,Argentina,2015,female,75+ years,27,1344980,2.01,Argentina2015,NaN,"594,749,285,413",14981,Silent
958,Argentina,2015,male,5-14 years,39,3672155,1.06,Argentina2015,NaN,"594,749,285,413",14981,Generation Z
959,Argentina,2015,female,5-14 years,19,3549219,0.54,Argentina2015,NaN,"594,749,285,413",14981,Generation Z
1236,Armenia,2015,male,75+ years,12,61355,19.56,Armenia2015,NaN,"10,553,337,673",3775,Silent
1237,Armenia,2015,male,55-74 years,16,231213,6.92,Armenia2015,NaN,"10,553,337,673",3775,Boomers
1238,Armenia,2015,female,75+ years,5,100754,4.96,Armenia2015,NaN,"10,553,337,673",3775,Silent
1239,Armenia,2015,male,35-54 years,15,356715,4.21,Armenia2015,NaN,"10,553,337,673",3775,Generation X
1240,Armenia,2015,male,25-34 years,10,255540,3.91,Armenia2015,NaN,"10,553,337,673",3775,Millenials
1241,Armenia,2015,female,55-74 years,5,297936,1.68,Armenia2015,NaN,"10,553,337,673",3775,Boomers
...,...,...,...,...,...,...,...,...,...,...,...,...
26842,United Kingdom,2015,female,55-74 years,306,7075576,4.32,United Kingdom2015,NaN,"2,885,570,309,161",47240,Boomers
26843,United Kingdom,2015,female,25-34 years,181,4414464,4.10,United Kingdom2015,NaN,"2,885,570,309,161",47240,Millenials
26844,United Kingdom,2015,female,75+ years,108,3070457,3.52,United Kingdom2015,NaN,"2,885,570,309,161",47240,Silent
26845,United Kingdom,2015,female,15-24 years,104,3966564,2.62,United Kingdom2015,NaN,"2,885,570,309,161",47240,Millenials
26846,United Kingdom,2015,female,5-14 years,6,3663221,0.16,United Kingdom2015,NaN,"2,885,570,309,161",47240,Generation Z
26847,United Kingdom,2015,male,5-14 years,4,3840476,0.10,United Kingdom2015,NaN,"2,885,570,309,161",47240,Generation Z
27208,United States,2015,male,75+ years,3171,8171136,38.81,United States2015,NaN,"18,120,714,000,000",60387,Silent
27209,United States,2015,male,55-74 years,9068,32264697,28.11,United States2015,NaN,"18,120,714,000,000",60387,Boomers
27210,United States,2015,male,35-54 years,11634,41658010,27.93,United States2015,NaN,"18,120,714,000,000",60387,Generation X
27211,United States,2015,male,25-34 years,5503,22137097,24.86,United States2015,NaN,"18,120,714,000,000",60387,Millenials
27212,United States,2015,male,15-24 years,4359,22615073,19.27,United States2015,NaN,"18,120,714,000,000",60387,Millenials
27213,United States,2015,female,35-54 years,4053,41531809,9.76,United States2015,NaN,"18,120,714,000,000",60387,Generation X
27214,United States,2015,female,55-74 years,2872,35115610,8.18,United States2015,NaN,"18,120,714,000,000",60387,Boomers
27215,United States,2015,female,25-34 years,1444,21555712,6.70,United States2015,NaN,"18,120,714,000,000",60387,Millenials
27216,United States,2015,female,15-24 years,1132,21633813,5.23,United States2015,NaN,"18,120,714,000,000",60387,Millenials
27217,United States,2015,female,75+ years,540,11778666,4.58,United States2015,NaN,"18,120,714,000,000",60387,Silent
27218,United States,2015,male,5-14 years,255,21273987,1.20,United States2015,NaN,"18,120,714,000,000",60387,Generation Z
27219,United States,2015,female,5-14 years,158,20342901,0.78,United States2015,NaN,"18,120,714,000,000",60387,Generation Z
27544,Uruguay,2015,male,75+ years,58,78996,73.42,Uruguay2015,NaN,"53,274,304,222",16696,Silent
27545,Uruguay,2015,male,55-74 years,133,277870,47.86,Uruguay2015,NaN,"53,274,304,222",16696,Boomers
27546,Uruguay,2015,male,25-34 years,96,235597,40.75,Uruguay2015,NaN,"53,274,304,222",16696,Millenials
27547,Uruguay,2015,male,35-54 years,135,423963,31.84,Uruguay2015,NaN,"53,274,304,222",16696,Generation X
27548,Uruguay,2015,male,15-24 years,74,264562,27.97,Uruguay2015,NaN,"53,274,304,222",16696,Millenials
27549,Uruguay,2015,female,75+ years,17,160620,10.58,Uruguay2015,NaN,"53,274,304,222",16696,Silent
27550,Uruguay,2015,female,55-74 years,34,327405,10.38,Uruguay2015,NaN,"53,274,304,222",16696,Boomers
27551,Uruguay,2015,female,25-34 years,23,232133,9.91,Uruguay2015,NaN,"53,274,304,222",16696,Millenials
27552,Uruguay,2015,female,35-54 years,38,440475,8.63,Uruguay2015,NaN,"53,274,304,222",16696,Generation X
27553,Uruguay,2015,female,15-24 years,17,255067,6.66,Uruguay2015,NaN,"53,274,304,222",16696,Millenials
27554,Uruguay,2015,male,5-14 years,3,252509,1.19,Uruguay2015,NaN,"53,274,304,222",16696,Generation Z
27555,Uruguay,2015,female,5-14 years,2,241598,0.83,Uruguay2015,NaN,"53,274,304,222",16696,Generation Z

In [14]:
grouped= data1['suicides_no'].groupby(data1['country']).sum()
grouped

country
Antigua and Barbuda                 1
Argentina                        3073
Armenia                            74
Australia                        3027
Austria                          1251
Belgium                          1867
Belize                             26
Brazil                          11163
Chile                            1838
Colombia                         2332
Croatia                           739
Cuba                             1511
Cyprus                             40
Czech Republic                   1387
Denmark                           564
Ecuador                          1073
Estonia                           195
Finland                           731
Georgia                           192
Germany                         10088
Greece                            529
Grenada                             0
Guatemala                         494
Hungary                          1868
Iceland                            40
Israel                            342
Italy                            3988
Japan                           23092
Kazakhstan                       2872
Kyrgyzstan                        417
                                ...
Luxembourg                         64
Malta                              34
Mauritius                         104
Mexico                           6234
Netherlands                      1873
Nicaragua                         315
Norway                            590
Panama                            110
Poland                           5420
Puerto Rico                       226
Qatar                              66
Republic of Korea               13510
Romania                          2228
Russian Federation              25432
Saint Vincent and Grenadines        3
Serbia                           1062
Seychelles                          7
Singapore                         329
Slovenia                          422
South Africa                      482
Spain                            3604
Sweden                           1182
Switzerland                      1073
Thailand                         4205
Turkey                           1532
Turkmenistan                      133
Ukraine                          7574
United Kingdom                   4910
United States                   44189
Uruguay                           630
Name: suicides_no, Length: 62, dtype: int64